kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "mlbparks-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/dulecux/adv-homework_template.git"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: MLBParks/Jenkinsfile
